#Ключ стоит 50 рублей
key: ""
#Настройка удара
Damage: 1
#Сообщение при смерти игрока
DeathMessage: "&7Игрок %player% заматерился до смерти и умер!"
#Звук если игрок сматерился
CustomSound: Sound.ENTITY_SILVERFISH_AMBIENT
#Если значение true, то слово будет удалятся
DelMessage: false
#Слова за которые идут удара
Words:
  - "блять"
  - "сук"
  - "cyka"